 					<option value="">-- Select University --</option>
					<option value="University Outside India">University Outside India</option>
					<option value="A.K.S. University">A.K.S. University</option>
					<option value="A.P.G.(Alakh Prakash Goyal) University">A.P.G.(Alakh Prakash Goyal) University</option>
					<option value="Academy of Maritime Education and Training">Academy of Maritime Education and Training</option>
					<option value="Acharya N.G. Ranga Agricultural University">Acharya N.G. Ranga Agricultural University</option>
					<option value="Acharya Nagarjuna University">Acharya Nagarjuna University</option>
					<option value="Adesh University">Adesh University</option>
					<option value="Adikavi Nannaya University">Adikavi Nannaya University</option>
					<option value="Ahmedabad University">Ahmedabad University</option>
					<option value="AISECT University">AISECT University</option>
					<option value="Alagappa University">Alagappa University</option>
					<option value="Al-Falah University">Al-Falah University</option>
					<option value="Aliah University">Aliah University</option>
					<option value="Aligarh Muslim University">Aligarh Muslim University</option>
					<option value="All India Institute of Medical Sciences">All India Institute of Medical Sciences</option>
					<option value="Alliance University">Alliance University</option>
					<option value="Amity University  UTTAR PRADESH">Amity University  UTTAR PRADESH</option>
					<option value="Amity University HARYANA">Amity University HARYANA</option>
					<option value="Amity University MADHYA PRADESH">Amity University MADHYA PRADESH</option>
					<option value="Amity University RAJASTHAN">Amity University RAJASTHAN</option>
					<option value="Amrita Vishwa Vidyapeetham">Amrita Vishwa Vidyapeetham</option>
					<option value="Anand Agricultural University">Anand Agricultural University</option>
					<option value="Andhra University">Andhra University</option>
					<option value="Anna university">Anna university</option>
					<option value="Anna University of Technology, Chennai TAMILNADU">Anna University of Technology, Chennai TAMILNADU</option>
					<option value="Anna University of Technology, Coimbatore TAMILNADU">Anna University of Technology, Coimbatore TAMILNADU</option>
					<option value="Anna University of Technology, Madurai TAMILNADU">Anna University of Technology, Madurai TAMILNADU</option>
					<option value="Anna University of Technology, Tiruchirappalli TAMILNADU">Anna University of Technology, Tiruchirappalli TAMILNADU</option>
					<option value="Anna University of Technology, Tirunelveli TAMILNADU">Anna University of Technology, Tirunelveli TAMILNADU</option>
					<option value="Annamalai University">Annamalai University</option>
					<option value="Ansal University">Ansal University</option>
					<option value="Apeejay Stya University">Apeejay Stya University</option>
					<option value="Apex Professional University">Apex Professional University</option>
					<option value="Arni University">Arni University</option>
					<option value="Arunachal University of Studies">Arunachal University of Studies</option>
					<option value="Aryabhatta knowledge University">Aryabhatta knowledge University</option>
					<option value="Ashoka University">Ashoka University</option>
					<option value="Assam Agricultural University">Assam Agricultural University</option>
					<option value="Assam Don Bosco University">Assam Don Bosco University</option>
					<option value="Assam Down Town University">Assam Down Town University</option>
					<option value="Assam Rajiv Gandhi University of Co-operative Management">Assam Rajiv Gandhi University of Co-operative Management</option>
					<option value="Assam Science &amp; Technology University">Assam Science &amp; Technology University</option>
					<option value="Assam University">Assam University</option>
					<option value="Atal Bihari Vajpai Hindi Vishwavidyalaya">Atal Bihari Vajpai Hindi Vishwavidyalaya</option>
					<option value="AURO University of Hospitality and Management">AURO University of Hospitality and Management</option>
					<option value="Avinashilingam Institute for Home Science &amp; Higher Education for Women">Avinashilingam Institute for Home Science &amp; Higher Education for Women</option>
					<option value="Awadhesh Pratap Singh University">Awadhesh Pratap Singh University</option>
					<option value="Ayush and Health Sciences University of Chhattisgarh">Ayush and Health Sciences University of Chhattisgarh</option>
					<option value="Azim Premji University">Azim Premji University</option>
					<option value="Dr. B. R. Ambedkar National Institute of Technology Jalandhar">Dr. B. R. Ambedkar National Institute of Technology Jalandhar</option>
					<option value="B.L.D.E. University">B.L.D.E. University</option>
					<option value="B.S. Abdur Rahman Institute of Science and Technology">B.S. Abdur Rahman Institute of Science and Technology</option>
					<option value="Baba Farid University of Health Sciences">Baba Farid University of Health Sciences</option>
					<option value="Baba Ghulam Shah Badshah University">Baba Ghulam Shah Badshah University</option>
					<option value="Baba Mast Nath University">Baba Mast Nath University</option>
					<option value="Babasaheb Bhimrao Ambedkar Bihar University">Babasaheb Bhimrao Ambedkar Bihar University</option>
					<option value="Babasaheb Bhimrao Ambedkar University">Babasaheb Bhimrao Ambedkar University</option>
					<option value="Babu Banarasi Das University">Babu Banarasi Das University</option>
					<option value="Baddi University of Emerging Sciences &amp; Technology">Baddi University of Emerging Sciences &amp; Technology</option>
					<option value="Bahra University">Bahra University</option>
					<option value="Banaras Hindu University">Banaras Hindu University</option>
					<option value="Banasthali Vidyapith">Banasthali Vidyapith</option>
					<option value="Bangalore University">Bangalore University</option>
					<option value="Barkatullah University">Barkatullah University</option>
					<option value="Bastar Vishwavidyalaya">Bastar Vishwavidyalaya</option>
					<option value="Berhampur University">Berhampur University</option>
					<option value="Bhagat Phool Singh Mahila Vishwavidyalaya">Bhagat Phool Singh Mahila Vishwavidyalaya</option>
					<option value="Bhagwant University">Bhagwant University</option>
					<option value="Bharat Ratna Dr. B.R. Ambedkar University NCT OF DELHI">Bharat Ratna Dr. B.R. Ambedkar University NCT OF DELHI</option>
					<option value="Bharath Institute of Higher Education &amp; Research">Bharath Institute of Higher Education &amp; Research</option>
					<option value="Bharathiar University">Bharathiar University</option>
					<option value="Bharathidasan University">Bharathidasan University</option>
					<option value="Bharati Vidyapeeth">Bharati Vidyapeeth</option>
					<option value="Bhatkhande Music Institute">Bhatkhande Music Institute</option>
					<option value="Bhupendra Narayan Mandal University">Bhupendra Narayan Mandal University</option>
					<option value="Bidhan Chandra Krishi Vishwavidyalaya">Bidhan Chandra Krishi Vishwavidyalaya</option>
					<option value="Bihar Agricultural University">Bihar Agricultural University</option>
					<option value="Bihar Yoga Bharati">Bihar Yoga Bharati</option>
					<option value="Biju Patnaik University of Technology">Biju Patnaik University of Technology</option>
					<option value="Bilaspur Vishwavidyalaya">Bilaspur Vishwavidyalaya</option>
					<option value="Birla Institute of Technology">Birla Institute of Technology</option>
					<option value="Birla Institute of Technology &amp; Science">Birla Institute of Technology &amp; Science</option>
					<option value="Birsa Agricultural University">Birsa Agricultural University</option>
					<option value="BML Munjal University">BML Munjal University</option>
					<option value="Bodoland University">Bodoland University</option>
					<option value="Bundelkhand University">Bundelkhand University</option>
					<option value="Burdwan University">Burdwan University</option>
					<option value="C.U. Shah University">C.U. Shah University</option>
					<option value="Calcutta University">Calcutta University</option>
					<option value="Calicut University">Calicut University</option>
					<option value="Calorx Teacher’s University">Calorx Teacher’s University</option>
					<option value="Career Point University HIMACHAL PRADESH">Career Point University HIMACHAL PRADESH</option>
					<option value="Career Point University RAJASTHAN">Career Point University RAJASTHAN</option>
					<option value="Central Agricultural University">Central Agricultural University</option>
					<option value="Central Institute of Fisheries Education">Central Institute of Fisheries Education</option>
					<option value="Central Institute of Higher Tibetan Studies">Central Institute of Higher Tibetan Studies</option>
					<option value="Central of University of Kashmir">Central of University of Kashmir</option>
					<option value="Central University of Bihar">Central University of Bihar</option>
					<option value="Central University of Gujarat">Central University of Gujarat</option>
					<option value="Central University of Haryana">Central University of Haryana</option>
					<option value="Central University of Himachal Pradesh">Central University of Himachal Pradesh</option>
					<option value="Central University of Jammu">Central University of Jammu</option>
					<option value="Central University of Jharkhand">Central University of Jharkhand</option>
					<option value="Central University of Karnataka">Central University of Karnataka</option>
					<option value="Central University of Kerala">Central University of Kerala</option>
					<option value="Central University of Orissa">Central University of Orissa</option>
					<option value="Central University of Punjab">Central University of Punjab</option>
					<option value="Central University of Rajasthan">Central University of Rajasthan</option>
					<option value="Central University of Tamil Nadu">Central University of Tamil Nadu</option>
					<option value="Centre for Environmental Planning and Technology University">Centre for Environmental Planning and Technology University</option>
					<option value="Centurion University of Technology and Management">Centurion University of Technology and Management</option>
					<option value="Chanakya National Law University">Chanakya National Law University</option>
					<option value="Chandigarh University">Chandigarh University</option>
					<option value="Chandra Shekhar Azad University of Agriculture &amp; Technology">Chandra Shekhar Azad University of Agriculture &amp; Technology</option>
					<option value="Charotar University of Science &amp; Technology">Charotar University of Science &amp; Technology</option>
					<option value="Chatrapati Sahuji Maharaj Kanpur University">Chatrapati Sahuji Maharaj Kanpur University</option>
					<option value="Chaudhary Devi Lal University">Chaudhary Devi Lal University</option>
					<option value="Chaudhary Sarwan Kumar Himachal Pradesh Krishi">Chaudhary Sarwan Kumar Himachal Pradesh Krishi</option>
					<option value="Chennai Mathematical Institute">Chennai Mathematical Institute</option>
					<option value="Chettinad Academy of Research and Education (CARE)">Chettinad Academy of Research and Education (CARE)</option>
					<option value="Chhattisgarh Kamdhenu Vishwavidyalaya">Chhattisgarh Kamdhenu Vishwavidyalaya</option>
					<option value="Chhattisgarh Swami Vivekanand Technical University">Chhattisgarh Swami Vivekanand Technical University</option>
					<option value="Children’s University">Children’s University</option>
					<option value="Chitkara University HIMACHAL PRADESH">Chitkara University HIMACHAL PRADESH</option>
					<option value="Chitkara University PUNJAB">Chitkara University PUNJAB</option>
					<option value="Chaudhary Charan Singh Haryana Agricultural University">Chaudhary Charan Singh Haryana Agricultural University</option>
					<option value="Chaudhary Charan Singh University">Chaudhary Charan Singh University</option>
					<option value="Christ College">Christ College</option>
					<option value="CMJ University">CMJ University</option>
					<option value="CMR University">CMR University</option>
					<option value="Cochin University of Science &amp; Technology">Cochin University of Science &amp; Technology</option>
					<option value="Cotton College State University">Cotton College State University</option>
					<option value="D.A.V. University">D.A.V. University</option>
					<option value="D.Y. Patil Educational Society">D.Y. Patil Educational Society</option>
					<option value="Dakshina Bharat Hindi Prachar Sabha">Dakshina Bharat Hindi Prachar Sabha</option>
					<option value="Damodaram Sanjivayya National Law University">Damodaram Sanjivayya National Law University</option>
					<option value="Datta Meghe Institute of Medical Sciences">Datta Meghe Institute of Medical Sciences</option>
					<option value="Davangere University">Davangere University</option>
					<option value="Dayalbagh Educational Institute">Dayalbagh Educational Institute</option>
					<option value="Dayananda Sagar University">Dayananda Sagar University</option>
					<option value="Deccan College of Post-Graduate &amp; Research Institute">Deccan College of Post-Graduate &amp; Research Institute</option>
					<option value="Deen Bandhu Chhotu Ram University of Science &amp; Technology">Deen Bandhu Chhotu Ram University of Science &amp; Technology</option>
					<option value="Deen Dayal Upadhyay Gorakhpur University">Deen Dayal Upadhyay Gorakhpur University</option>
					<option value="Delhi Technological University">Delhi Technological University</option>
					<option value="Delhi University">Delhi University</option>
					<option value="Desh Bhagat University">Desh Bhagat University</option>
					<option value="Dev Sanskriti Vishwavidyalaya">Dev Sanskriti Vishwavidyalaya</option>
					<option value="Devi Ahilya Vishwavidyalaya">Devi Ahilya Vishwavidyalaya</option>
					<option value="Dharmsinh Desai University">Dharmsinh Desai University</option>
					<option value="Dhirubhai Ambani Institute of Information and Communication Technology">Dhirubhai Ambani Institute of Information and Communication Technology</option>
					<option value="Dibrugarh University">Dibrugarh University</option>
					<option value="DIT University">DIT University</option>
					<option value="Doon University">Doon University</option>
					<option value="Dr. Harisingh Gour Vishwavidyalaya">Dr. Harisingh Gour Vishwavidyalaya</option>
					<option value="Dr. Ram Manohar Lohia Awadh University">Dr. Ram Manohar Lohia Awadh University</option>
					<option value="Dr. B.R. Ambedkar Open University">Dr. B.R. Ambedkar Open University</option>
					<option value="Dr. B.R. Ambedkar University ANDHRA PRADESH">Dr. B.R. Ambedkar University ANDHRA PRADESH</option>
					<option value="Dr. B.R. Ambedkar University UTTAR PRADESH">Dr. B.R. Ambedkar University UTTAR PRADESH</option>
					<option value="Dr. Babasaheb Ambedkar Marathwada University">Dr. Babasaheb Ambedkar Marathwada University</option>
					<option value="Dr. Babasaheb Ambedkar Open University">Dr. Babasaheb Ambedkar Open University</option>
					<option value="Dr. Babasaheb Ambedkar Technological University">Dr. Babasaheb Ambedkar Technological University</option>
					<option value="Dr. Bhimrao Ambedkar Law University">Dr. Bhimrao Ambedkar Law University</option>
					<option value="Dr. C.V. Raman University">Dr. C.V. Raman University</option>
					<option value="Dr. D.Y. Patil Vidyapeeth">Dr. D.Y. Patil Vidyapeeth</option>
					<option value="Dr. K.N. Modi University">Dr. K.N. Modi University</option>
					<option value="Dr. N.T.R. University of Health Sciences (Formerly Andhra Pradesh University">Dr. N.T.R. University of Health Sciences (Formerly Andhra Pradesh University</option>
					<option value="Dr. Panjabrao Deshmukh Krishi Vidyapeeth">Dr. Panjabrao Deshmukh Krishi Vidyapeeth</option>
					<option value="Dr. Ram Manohar Lohiya National Law University">Dr. Ram Manohar Lohiya National Law University</option>
					<option value="Dr. Y.S.Parmar University of Horticulture &amp; Forestry">Dr. Y.S.Parmar University of Horticulture &amp; Forestry</option>
					<option value="Dr. Y.S.R. Horticultural University">Dr. Y.S.R. Horticultural University</option>
					<option value="Dravidian University">Dravidian University</option>
					<option value="Eastern Institute for integrated Learning in Management University">Eastern Institute for integrated Learning in Management University</option>
					<option value="Eternal University">Eternal University</option>
					<option value="Fakir Mohan University">Fakir Mohan University</option>
					<option value="Forest Research Institute">Forest Research Institute</option>
					<option value="G.B. Pant University of Agriculture and Technology">G.B. Pant University of Agriculture and Technology</option>
					<option value="G.D. Goenka University">G.D. Goenka University</option>
					<option value="G.L.A. University">G.L.A. University</option>
					<option value="Galgotias University">Galgotias University</option>
					<option value="Gandhi Institute of Technology and Management (GITAM)">Gandhi Institute of Technology and Management (GITAM)</option>
					<option value="Gandhigram Rural Institute">Gandhigram Rural Institute</option>
					<option value="Ganpat University">Ganpat University</option>
					<option value="Gauhati University">Gauhati University</option>
					<option value="Gour Banga University">Gour Banga University</option>
					<option value="Gautam Buddha University">Gautam Buddha University</option>
					<option value="Gautam Buddh Technical University">Gautam Buddh Technical University</option>
					<option value="Geetanjali University">Geetanjali University</option>
					<option value="Goa University">Goa University</option>
					<option value="Gokhale Institute of Politics &amp; Economics">Gokhale Institute of Politics &amp; Economics</option>
					<option value="Gondwana University">Gondwana University</option>
					<option value="Graphic Era Parvatiya Vishwavidyalaya">Graphic Era Parvatiya Vishwavidyalaya</option>
					<option value="Graphic Era University">Graphic Era University</option>
					<option value="Gujarat Agricultural University">Gujarat Agricultural University</option>
					<option value="Gujarat Ayurveda University">Gujarat Ayurveda University</option>
					<option value="Gujarat Forensic Sciences University">Gujarat Forensic Sciences University</option>
					<option value="Gujarat National Law University">Gujarat National Law University</option>
					<option value="Gujarat Technological University">Gujarat Technological University</option>
					<option value="Gujarat University">Gujarat University</option>
					<option value="Gujarat Vidyapith">Gujarat Vidyapith</option>
					<option value="Gulbarga University">Gulbarga University</option>
					<option value="Guru Angad Dev Veterinary &amp; Animal Sciences University">Guru Angad Dev Veterinary &amp; Animal Sciences University</option>
					<option value="Guru Ghasidas Vishwavidyalaya">Guru Ghasidas Vishwavidyalaya</option>
					<option value="Guru Gobind Singh Indraprastha Vishwavidyalaya">Guru Gobind Singh Indraprastha Vishwavidyalaya</option>
					<option value="Guru Jambheshwar University of Science and Technology">Guru&#160;Jambheshwar&#160;University of Science and Technology</option>
					<option value="Guru Kashi University">Guru Kashi University</option>
					<option value="Guru Nanak Dev University">Guru Nanak Dev University</option>
					<option value="Guru Ravidas Ayurved University">Guru Ravidas Ayurved University</option>
					<option value="Gurukul Kangri Vishwavidyalaya">Gurukul Kangri Vishwavidyalaya</option>
					<option value="Haridev Joshi University of Journalism &amp; Mass Communication">Haridev Joshi University of Journalism &amp; Mass Communication</option>
					<option value="Hemchandracharya North Gujarat University">Hemchandracharya North Gujarat University</option>
					<option value="Hemwati Nandan Bahuguna Garhwal University">Hemwati Nandan Bahuguna Garhwal University</option>
					<option value="Hemwati Nandan Bahuguna Medical Education University">Hemwati Nandan Bahuguna Medical Education University</option>
					<option value="Hidayatullah National Law University">Hidayatullah National Law University</option>
					<option value="HIHT University">HIHT University</option>
					<option value="Himachal Pradesh Technical University">Himachal Pradesh Technical University</option>
					<option value="Himachal Pradesh University">Himachal Pradesh University</option>
					<option value="Himalayan University">Himalayan University</option>
					<option value="Himgiri Zee University">Himgiri Zee University</option>
					<option value="Hindustan Institute of Technology and Science (HITS)">Hindustan Institute of Technology and Science (HITS)</option>
					<option value="Homeopathy University">Homeopathy University</option>
					<option value="Homi Bhabha National Institute">Homi Bhabha National Institute</option>
					<option value="I.E.C. (India Education Centre) University">I.E.C. (India Education Centre) University</option>
					<option value="ICFAI Foundation for Higher Education">ICFAI Foundation for Higher Education</option>
					<option value="ICFAI University CHHATTISGARH">ICFAI University CHHATTISGARH</option>
					<option value="ICFAI University HIMACHAL PRADESH">ICFAI University HIMACHAL PRADESH</option>
					<option value="ICFAI University RAJASTHAN">ICFAI University RAJASTHAN</option>
					<option value="IFTM University">IFTM University</option>
					<option value="IIS University">IIS University</option>
					<option value="IMS Unison University">IMS Unison University</option>
					<option value="Indian Agricultural Research Institute">Indian Agricultural Research Institute</option>
					<option value="Indian Institute of Foreign Trade">Indian Institute of Foreign Trade</option>
					<option value="Indian Institute of Information Technology">Indian Institute of Information Technology</option>
					<option value="Indian Institute of Information Technology and Management">Indian Institute of Information Technology and Management</option>
					<option value="Indian Institute of Information Technology Design Manufacturing">Indian Institute of Information Technology Design Manufacturing</option>
					<option value="Indian Institute of Science">Indian Institute of Science</option>
					<option value="Indian Institute of Space Science and Technology">Indian Institute of Space Science and Technology</option>
					<option value="Indian Institute of Teacher Education">Indian Institute of Teacher Education</option>
					<option value="Indian Institute of Technology ANDHRA PRADESH">Indian Institute of Technology ANDHRA PRADESH</option>
					<option value="Indian Institute of Technology ASSAM">Indian Institute of Technology ASSAM</option>
					<option value="Indian Institute of Technology BIHAR">Indian Institute of Technology BIHAR</option>
					<option value="Indian Institute of Technology GUJARAT">Indian Institute of Technology GUJARAT</option>
					<option value="Indian Institute of Technology HIMACHAL PRADESH">Indian Institute of Technology HIMACHAL PRADESH</option>
					<option value="Indian Institute of Technology MADHYA PRADESH">Indian Institute of Technology MADHYA PRADESH</option>
					<option value="Indian Institute of Technology MAHARASHTRA">Indian Institute of Technology MAHARASHTRA</option>
					<option value="Indian Institute of Technology NCT OF DELHI">Indian Institute of Technology NCT OF DELHI</option>
					<option value="Indian Institute of Technology ORISSA">Indian Institute of Technology ORISSA</option>
					<option value="Indian Institute of Technology PUNJAB">Indian Institute of Technology PUNJAB</option>
					<option value="Indian Institute of Technology RAJASTHAN">Indian Institute of Technology RAJASTHAN</option>
					<option value="Indian Institute of Technology TAMILNADU">Indian Institute of Technology TAMILNADU</option>
					<option value="Indian Institute of Technology UTTAR PRADESH">Indian Institute of Technology UTTAR PRADESH</option>
					<option value="Indian Institute of Technology UTTARAKHAND">Indian Institute of Technology UTTARAKHAND</option>
					<option value="Indian Institute of Technology WEST BENGAL">Indian Institute of Technology WEST BENGAL</option>
					<option value="Indian Law Institute">Indian Law Institute</option>
					<option value="Indian Maritime University">Indian Maritime University</option>
					<option value="Indian School of Mines">Indian School of Mines</option>
					<option value="Indian Statistical Institute">Indian Statistical Institute</option>
					<option value="Indian Veterinary Research Institute">Indian Veterinary Research Institute</option>
					<option value="Indira Gandhi Delhi Technical University for Women">Indira Gandhi Delhi Technical University for Women</option>
					<option value="Indira Gandhi Institute of Development Research">Indira Gandhi Institute of Development Research</option>
					<option value="Indira Gandhi Krishi Vishwavidyalaya">Indira Gandhi Krishi Vishwavidyalaya</option>
					<option value="Indira Gandhi National Open University">Indira Gandhi National Open University</option>
					<option value="Indira Gandhi University">Indira Gandhi University</option>
					<option value="Indira Kala Sangeet Vishwavidyalaya">Indira Kala Sangeet Vishwavidyalaya</option>
					<option value="Indraprastha Institute of Information Technology Near Govindpuri Metro Station">Indraprastha Institute of Information Technology Near Govindpuri Metro Station</option>
					<option value="Indus International University">Indus International University</option>
					<option value="Indus University">Indus University</option>
					<option value="Institute of Advanced Studies in Education of Gandhi Vidya Mandir">Institute of Advanced Studies in Education of Gandhi Vidya Mandir</option>
					<option value="Institute of Armament Technology">Institute of Armament Technology</option>
					<option value="Institute of Chartered Financial Analysts of India">Institute of Chartered Financial Analysts of India</option>
					<option value="Institute of Chartered Financial Analysts of India (ICFAI)">Institute of Chartered Financial Analysts of India (ICFAI)</option>
					<option value="Institute of Chemical Technology">Institute of Chemical Technology</option>
					<option value="Institute of Liver and Biliary Sciences (ILBS)">Institute of Liver and Biliary Sciences (ILBS)</option>
					<option value="Integral University">Integral University</option>
					<option value="International Institute for Population Sciences">International Institute for Population Sciences</option>
					<option value="International Institute of Information Technology KARNATAKA">International Institute of Information Technology KARNATAKA</option>
					<option value="International Institute of Information Technology TELANGANA">International Institute of Information Technology TELANGANA</option>
					<option value="Invertis University">Invertis University</option>
					<option value="Islamic University of Science &amp; Technology University">Islamic University of Science &amp; Technology University</option>
					<option value="ITM University CHHATTISGARH">ITM University CHHATTISGARH</option>
					<option value="ITM University HARYANA">ITM University HARYANA</option>
					<option value="ITM University MADHYA PRADESH">ITM University MADHYA PRADESH</option>
					<option value="ITM-Vocational University">ITM-Vocational University</option>
					<option value="J.E.C.R.C. University">J.E.C.R.C. University</option>
					<option value="J.K. Lakshmipat University">J.K. Lakshmipat University</option>
					<option value="Jadavpur University">Jadavpur University</option>
					<option value="Jagadguru Ramanandacharya Rajasthan Sanskrit University">Jagadguru Ramanandacharya Rajasthan Sanskrit University</option>
					<option value="Jagadguru Rambhadracharya Handicapped University">Jagadguru Rambhadracharya Handicapped University</option>
					<option value="Jagadguru Sri Shivarathreeswara University">Jagadguru Sri Shivarathreeswara University</option>
					<option value="Jagan Nath University">Jagan Nath University</option>
					<option value="Jagannath University">Jagannath University</option>
					<option value="Jagran Lakecity University">Jagran Lakecity University</option>
					<option value="Jai Narain Vyas University">Jai Narain Vyas University</option>
					<option value="Jai Prakash University">Jai Prakash University</option>
					<option value="Jain University">Jain University</option>
					<option value="Jain Vishva Bharati Institute">Jain Vishva Bharati Institute</option>
					<option value="Jaipur National University">Jaipur National University</option>
					<option value="Jamia Hamdard">Jamia Hamdard</option>
					<option value="Jamia Mallia Islamia University">Jamia Mallia Islamia University</option>
					<option value="Jammu University">Jammu University</option>
					<option value="Janardan Rai Nagar Rajasthan Vidyapeeth">Janardan Rai Nagar Rajasthan Vidyapeeth</option>
					<option value="Jawaharlal Nehru Architecture and Fine Arts University">Jawaharlal Nehru Architecture and Fine Arts University</option>
					<option value="Jawaharlal Nehru Centre for Advanced Scientific Research">Jawaharlal Nehru Centre for Advanced Scientific Research</option>
					<option value="Jawaharlal Nehru Krishi Vishwavidyalaya">Jawaharlal Nehru Krishi Vishwavidyalaya</option>
					<option value="Jawaharlal Nehru Technological University, Anantpur ANDHRA PRADESH">Jawaharlal Nehru Technological University, Anantpur ANDHRA PRADESH</option>
					<option value="Jawaharlal Nehru Technological University, Kakinada ANDHRA PRADESH">Jawaharlal Nehru Technological University, Kakinada ANDHRA PRADESH</option>
					<option value="Jawaharlal Nehru Technological University, TELANGANA">Jawaharlal Nehru Technological University, TELANGANA</option>
					<option value="Jawaharlal Nehru University">Jawaharlal Nehru University</option>
					<option value="Jayoti Vidyapeeth Women’s University">Jayoti Vidyapeeth Women’s University</option>
					<option value="Jaypee Institute of Information Technology">Jaypee Institute of Information Technology</option>
					<option value="Jaypee University">Jaypee University</option>
					<option value="Jaypee University of Engineering &amp; Technology">Jaypee University of Engineering &amp; Technology</option>
					<option value="Jaypee University of Information Technology">Jaypee University of Information Technology</option>
					<option value="Jharkhand Rai University">Jharkhand Rai University</option>
					<option value="Jiwaji University">Jiwaji University</option>
					<option value="Jodhpur National University">Jodhpur National University</option>
					<option value="Junagarh Agricultural University">Junagarh Agricultural University</option>
					<option value="K.R. Mangalam University">K.R. Mangalam University</option>
					<option value="K.S.Darbhanga Sanskrit Vishwavidyalaya">K.S.Darbhanga Sanskrit Vishwavidyalaya</option>
					<option value="Kadi Sarva Vishwavidyalaya">Kadi Sarva Vishwavidyalaya</option>
					<option value="Kakatiya University">Kakatiya University</option>
					<option value="Kalasalingam Academy of Research and Higher Education">Kalasalingam Academy of Research and Higher Education</option>
					<option value="Kalinga Institute of Industrial Technology">Kalinga Institute of Industrial Technology</option>
					<option value="Kalinga University">Kalinga University</option>
					<option value="Kalyani University">Kalyani University</option>
					<option value="Kamdhenu University">Kamdhenu University</option>
					<option value="Kannada University">Kannada University</option>
					<option value="Kannur University">Kannur University</option>
					<option value="Karnataka Folklore University">Karnataka Folklore University</option>
					<option value="Karnataka Sanskrit University">Karnataka Sanskrit University</option>
					<option value="Karnataka State Law University">Karnataka State Law University</option>
					<option value="Karnataka State Open University">Karnataka State Open University</option>
					<option value="Karnataka State Women University">Karnataka State Women University</option>
					<option value="Karnataka University">Karnataka University</option>
					<option value="Karnataka Veterinary">Karnataka Veterinary</option>
					<option value="Karpagam Academy of Higher Education">Karpagam Academy of Higher Education</option>
					<option value="Karunya Institute of Technology and Sciences">Karunya Institute of Technology and Sciences</option>
					<option value="Kashmir University">Kashmir University</option>
					<option value="Kavi Kulguru Kalidas Sanskrit Vishwavidyalaya">Kavi Kulguru Kalidas Sanskrit Vishwavidyalaya</option>
					<option value="Kazi Nazrul University">Kazi Nazrul University</option>
					<option value="Kerala Agricultural University">Kerala Agricultural University</option>
					<option value="Kerala Kalamandalam">Kerala Kalamandalam</option>
					<option value="Kerala University">Kerala University</option>
					<option value="Kerala University of Fisheries &amp; Ocean Studies">Kerala University of Fisheries &amp; Ocean Studies</option>
					<option value="Kerala University of Health Sciences">Kerala University of Health Sciences</option>
					<option value="Kerala Veterinary &amp; Animal Sciences University">Kerala Veterinary &amp; Animal Sciences University</option>
					<option value="Khwaja Moinuddin Chishti Urdu">Khwaja Moinuddin Chishti Urdu</option>
					<option value="King George Medical University">King George Medical University</option>
					<option value="KLE Academy of Higher Education and Research">KLE Academy of Higher Education and Research</option>
					<option value="Kolhan University">Kolhan University</option>
					<option value="Koneru Lakshmaiah Education Foundation">Koneru Lakshmaiah Education Foundation</option>
					<option value="Konkan Krishi Vidyapeeth">Konkan Krishi Vidyapeeth</option>
					<option value="Krantiguru Shyamji Krishna Verma Kachchh University">Krantiguru Shyamji Krishna Verma Kachchh University</option>
					<option value="Krishna Institute of Medical Sciences">Krishna Institute of Medical Sciences</option>
					<option value="Krishna Kanta Handique State Open University">Krishna Kanta Handique State Open University</option>
					<option value="Krishna University">Krishna University</option>
					<option value="KSGH Music and Performing Arts University">KSGH Music and Performing Arts University</option>
					<option value="Kumar Bhaskar Varma Sanskrit &amp; ancient Studies University">Kumar Bhaskar Varma Sanskrit &amp; ancient Studies University</option>
					<option value="Kumaun University">Kumaun University</option>
					<option value="Kurukshetra University">Kurukshetra University</option>
					<option value="Kushabhau Thakre Patrakarita Avam Jansanchar Vishwavidyalaya">Kushabhau Thakre Patrakarita Avam Jansanchar Vishwavidyalaya</option>
					<option value="Kuvempu University">Kuvempu University</option>
					<option value="Lakshmibai National Institute of Physical Education">Lakshmibai National Institute of Physical Education</option>
					<option value="Lala Lajpat Rai University of Veterinary &amp; Animal Sciences">Lala Lajpat Rai University of Veterinary &amp; Animal Sciences</option>
					<option value="Lalit Narayan Mithila University">Lalit Narayan Mithila University</option>
					<option value="Lingaya’s University">Lingaya’s University</option>
					<option value="LNM Institute of Information Technology">LNM Institute of Information Technology</option>
					<option value="Lovely Professional University">Lovely Professional University</option>
					<option value="Lucknow University">Lucknow University</option>
					<option value="M.G.R. Educational and Research Institute">M.G.R. Educational and Research Institute</option>
					<option value="M.J.P. Rohilkhand University">M.J.P. Rohilkhand University</option>
					<option value="M.P. Bhoj (open) University">M.P. Bhoj (open) University</option>
					<option value="M.S. Ramaiah University of Applied Sciences">M.S. Ramaiah University of Applied Sciences</option>
					<option value="M.V.N. University">M.V.N. University</option>
					<option value="Madan Mohan Malviya University of Technology">Madan Mohan Malviya University of Technology</option>
					<option value="Madhav University">Madhav University</option>
					<option value="Madhya Pradesh Medical Science University">Madhya Pradesh Medical Science University</option>
					<option value="Madras University">Madras University</option>
					<option value="Madurai Kamraj University">Madurai Kamraj University</option>
					<option value="Magadh University">Magadh University</option>
					<option value="Mahamaya Technical University">Mahamaya Technical University</option>
					<option value="Maharaj Vinayak Global University">Maharaj Vinayak Global University</option>
					<option value="Maharaja Agrasen University">Maharaja Agrasen University</option>
					<option value="Maharaja Ganga Singh University">Maharaja Ganga Singh University</option>
					<option value="Maharaja Krishnakumarsinji Bhavnagar University">Maharaja Krishnakumarsinji Bhavnagar University</option>
					<option value="Maharaja Sayajirao University of Baroda">Maharaja Sayajirao University of Baroda</option>
					<option value="Maharaja University of Information Technology">Maharaja University of Information Technology</option>
					<option value="Maharana Pratap University of Agriculture &amp; Technology">Maharana Pratap University of Agriculture &amp; Technology</option>
					<option value="Maharashtra Animal &amp; Fishery Sciences University">Maharashtra Animal &amp; Fishery Sciences University</option>
					<option value="Maharashtra University of Health Sciences">Maharashtra University of Health Sciences</option>
					<option value="Maharishi Dayanand Saraswati University">Maharishi Dayanand Saraswati University</option>
					<option value="Maharishi Dayanand University">Maharishi Dayanand University</option>
					<option value="Maharishi Mahesh Yogi Vedic Vishwavidyalaya">Maharishi Mahesh Yogi Vedic Vishwavidyalaya</option>
					<option value="Maharishi Markandeshwar Education Trust">Maharishi Markandeshwar Education Trust</option>
					<option value="Maharishi Markandeshwar University HARYANA">Maharishi Markandeshwar University HARYANA</option>
					<option value="Maharishi Markandeshwar University HIMACHAL PRADESH">Maharishi Markandeshwar University HIMACHAL PRADESH</option>
					<option value="Maharishi Panini Sanskrit Evam Vedic Vishwavidyalaya">Maharishi Panini Sanskrit Evam Vedic Vishwavidyalaya</option>
					<option value="Maharishi University of Management and Technology">Maharishi University of Management and Technology</option>
					<option value="Mahatma Gandhi Antarrashtriya Hindi Vishwavidyalay">Mahatma Gandhi Antarrashtriya Hindi Vishwavidyalay</option>
					<option value="Mahatma Gandhi Chitrakoot Gramoday Vishwavidyalaya">Mahatma Gandhi Chitrakoot Gramoday Vishwavidyalaya</option>
					<option value="Mahatma Gandhi Kashi Vidyapeeth">Mahatma Gandhi Kashi Vidyapeeth</option>
					<option value="Mahatma Gandhi University KERALA">Mahatma Gandhi University KERALA</option>
					<option value="Mahatma Gandhi University MEGHALAYA">Mahatma Gandhi University MEGHALAYA</option>
					<option value="Mahatma Gandhi University of Medical Sciences &amp; Technology">Mahatma Gandhi University of Medical Sciences &amp; Technology</option>
					<option value="Mahatma Gandhi University TELANGANA">Mahatma Gandhi University TELANGANA</option>
					<option value="Mahatma Jyoti Rao Phule University">Mahatma Jyoti Rao Phule University</option>
					<option value="Mahatma Phule Krishi Vidyapeeth">Mahatma Phule Krishi Vidyapeeth</option>
					<option value="Makhanlal Chaturvedi Rashtriya Patrakarita National University of Journalism">Makhanlal Chaturvedi Rashtriya Patrakarita National University of Journalism</option>
					<option value="Malaviya National Institute of Technology RAJASTHAN">Malaviya National Institute of Technology RAJASTHAN</option>
					<option value="Manav Bharti University">Manav Bharti University</option>
					<option value="Manav Rachna International University">Manav Rachna International University</option>
					<option value="Mangalayatan University">Mangalayatan University</option>
					<option value="Mangalore University">Mangalore University</option>
					<option value="Manipal Academy of Higher Education">Manipal Academy of Higher Education</option>
					<option value="Manipal University">Manipal University</option>
					<option value="Manipur University">Manipur University</option>
					<option value="Manonmaniam Sundarnar University">Manonmaniam Sundarnar University</option>
					<option value="Marathwada Agricultural University">Marathwada Agricultural University</option>
					<option value="Martin Luther Christian University">Martin Luther Christian University</option>
					<option value="MATS University">MATS University</option>
					<option value="Maulana Azad National Urdu University">Maulana Azad National Urdu University</option>
					<option value="Maulana Azad University">Maulana Azad University</option>
					<option value="Maulana Mazharul Haque Arabic &amp; Persian University">Maulana Mazharul Haque Arabic &amp; Persian University</option>
					<option value="Maulana Azad National Institute of Technology MADHYA PRADESH">Maulana Azad National Institute of Technology MADHYA PRADESH</option>
					<option value="Meenakshi Academy of Higher Education and Research">Meenakshi Academy of Higher Education and Research</option>
					<option value="Mewar University">Mewar University</option>
					<option value="MGM Institute of Health Sciences">MGM Institute of Health Sciences</option>
					<option value="Mizoram University">Mizoram University</option>
					<option value="Mody Institute of Technology and Science">Mody Institute of Technology and Science</option>
					<option value="Mohammad Ali Jauhar University">Mohammad Ali Jauhar University</option>
					<option value="Mohan Lal Sukhadia University">Mohan Lal Sukhadia University</option>
					<option value="Monad University">Monad University</option>
					<option value="Mother Teresa Women’s University">Mother Teresa Women’s University</option>
					<option value="Motilal Nehru National Institute of Technology UTTAR PRADESH">Motilal Nehru National Institute of Technology UTTAR PRADESH</option>
					<option value="Mumbai University">Mumbai University</option>
					<option value="Mysore University">Mysore University</option>
					<option value="Nagaland University">Nagaland University</option>
					<option value="Nalanda Open University">Nalanda Open University</option>
					<option value="Nalanda University">Nalanda University</option>
					<option value="Nanaji Deshmukh Pashu Chikitsa Vigyan Vishwavidyalaya">Nanaji Deshmukh Pashu Chikitsa Vigyan Vishwavidyalaya</option>
					<option value="Narendra Deo University of Agriculture &amp; Technology">Narendra Deo University of Agriculture &amp; Technology</option>
					<option value="Narsee Monjee Institute of Management Studies">Narsee Monjee Institute of Management Studies</option>
					<option value="National Academy of Legal Studies &amp; Research University">National Academy of Legal Studies &amp; Research University</option>
					<option value="National Brain Research Centre">National Brain Research Centre</option>
					<option value="National Dairy Research Institute">National Dairy Research Institute</option>
					<option value="National Institute of Technology ARUNACHAL PRADESH">National Institute of Technology ARUNACHAL PRADESH</option>
					<option value="National Institute of Technology GOA">National Institute of Technology GOA</option>
					<option value="National Institute of Educational Planning and Administration">National Institute of Educational Planning and Administration</option>
					<option value="National Institute of Food Technology Entrepreneurship and Management">National Institute of Food Technology Entrepreneurship and Management</option>
					<option value="National Institute of Mental Health &amp; Neuro Sciences">National Institute of Mental Health &amp; Neuro Sciences</option>
					<option value="National Institute of Pharmaceutical Education and Research">National Institute of Pharmaceutical Education and Research</option>
					<option value="National Institute of Technology TELANGANA">National Institute of Technology TELANGANA</option>
					<option value="National Institute of Technology ASSAM">National Institute of Technology ASSAM</option>
					<option value="National Institute of Technology BIHAR">National Institute of Technology BIHAR</option>
					<option value="National Institute of Technology CHHATTISGARH">National Institute of Technology CHHATTISGARH</option>
					<option value="National Institute of Technology HARYANA">National Institute of Technology HARYANA</option>
					<option value="National Institute of Technology HIMACHAL PRADESH">National Institute of Technology HIMACHAL PRADESH</option>
					<option value="National Institute of Technology JAMMU &amp; KASHMIR">National Institute of Technology JAMMU &amp; KASHMIR</option>
					<option value="National Institute of Technology JHARKHAND">National Institute of Technology JHARKHAND</option>
					<option value="National Institute of Technology KARNATAKA">National Institute of Technology KARNATAKA</option>
					<option value="National Institute of Technology KERALA">National Institute of Technology KERALA</option>
					<option value="National Institute of Technology MANIPUR">National Institute of Technology MANIPUR</option>
					<option value="National Institute of Technology MEGHALAYA">National Institute of Technology MEGHALAYA</option>
					<option value="National Institute of Technology MIZORAM">National Institute of Technology MIZORAM</option>
					<option value="National Institute of Technology NAGALAND">National Institute of Technology NAGALAND</option>
					<option value="National Institute of Technology NCT OF DELHI">National Institute of Technology NCT OF DELHI</option>
					<option value="National Institute of Technology ORISSA">National Institute of Technology ORISSA</option>
					<option value="National Institute of Technology PONDICHERRY">National Institute of Technology PONDICHERRY</option>
					<option value="National Institute of Technology SIKKIM">National Institute of Technology SIKKIM</option>
					<option value="National Institute of Technology TAMILNADU">National Institute of Technology TAMILNADU</option>
					<option value="National Institute of Technology TRIPURA">National Institute of Technology TRIPURA</option>
					<option value="National Institute of Technology UTTARAKHAND">National Institute of Technology UTTARAKHAND</option>
					<option value="National Institute of Technology WEST BENGAL">National Institute of Technology WEST BENGAL</option>
					<option value="National Law Institute University">National Law Institute University</option>
					<option value="National law School of India University">National law School of India University</option>
					<option value="National Law University and Judicial Academy">National Law University and Judicial Academy</option>
					<option value="National law University NCT OF DELHI">National law University NCT OF DELHI</option>
					<option value="National law University ORISSA">National law University ORISSA</option>
					<option value="National law University RAJASTHAN">National law University RAJASTHAN</option>
					<option value="National Museum Institute of History of Art, Conservation and Museology">National Museum Institute of History of Art, Conservation and Museology</option>
					<option value="National University of Advanced Legal Studies (NUALS)">National University of Advanced Legal Studies (NUALS)</option>
					<option value="National University of Study &amp; Research in Law">National University of Study &amp; Research in Law</option>
					<option value="Nava Nalanda Mahavihara">Nava Nalanda Mahavihara</option>
					<option value="Navrachana University">Navrachana University</option>
					<option value="Nehru Gram Bharati Vishwavidyalaya">Nehru Gram Bharati Vishwavidyalaya</option>
					<option value="Netaji Subhash Open University">Netaji Subhash Open University</option>
					<option value="NIILM University">NIILM University</option>
					<option value="NIIT University">NIIT University</option>
					<option value="Nilamber-Pitamber University">Nilamber-Pitamber University</option>
					<option value="NIMS University">NIMS University</option>
					<option value="Nirma University of Science &amp; Technology">Nirma University of Science &amp; Technology</option>
					<option value="NITTE University">NITTE University</option>
					<option value="Noida International University">Noida International University</option>
					<option value="Noorul Islam Centre for Higher Education">Noorul Islam Centre for Higher Education</option>
					<option value="North Bengal University">North Bengal University</option>
					<option value="North Eastern Hill University">North Eastern Hill University</option>
					<option value="North Eastern Regional Institute of Science &amp; Technology">North Eastern Regional Institute of Science &amp; Technology</option>
					<option value="North Maharashtra University">North Maharashtra University</option>
					<option value="North Orissa University">North Orissa University</option>
					<option value="O.P. Jindal Global University">O.P. Jindal Global University</option>
					<option value="OPJS University">OPJS University</option>
					<option value="Oriental University">Oriental University</option>
					<option value="Orissa University of Agriculture &amp; Technology">Orissa University of Agriculture &amp; Technology</option>
					<option value="Osmania University">Osmania University</option>
					<option value="Others">Others</option>
					<option value="Pacific Academic of Higher Education &amp; Research University">Pacific Academic of Higher Education &amp; Research University</option>
					<option value="Pacific Medical University">Pacific Medical University</option>
					<option value="Padmashree Dr. D.Y. Patil Vidyapeeth">Padmashree Dr. D.Y. Patil Vidyapeeth</option>
					<option value="Palamuru University">Palamuru University</option>
					<option value="Pandit Deendayal Petroleum University">Pandit Deendayal Petroleum University</option>
					<option value="Pandit Dwarka Prasad Mishra Indian Institute of Information Technology, Design &amp; Manufacturing">Pandit Dwarka Prasad Mishra Indian Institute of Information Technology, Design &amp; Manufacturing</option>
					<option value="Patna University">Patna University</option>
					<option value="People’s University">People’s University</option>
					<option value="Periyar Maniammai Institute of Science &amp; Technology (PMIST)">Periyar Maniammai Institute of Science &amp; Technology (PMIST)</option>
					<option value="Periyar University">Periyar University</option>
					<option value="PES University">PES University</option>
					<option value="Pondicherry University">Pondicherry University</option>
					<option value="Ponnaiyah Ramajayam Institute of Science &amp; Technology (PRIST)">Ponnaiyah Ramajayam Institute of Science &amp; Technology (PRIST)</option>
					<option value="Poornima University">Poornima University</option>
					<option value="Post-Graduate Institute of Medical Education &amp; Research">Post-Graduate Institute of Medical Education &amp; Research</option>
					<option value="Potti Sreeramulu Telugu University">Potti Sreeramulu Telugu University</option>
					<option value="Pratap University">Pratap University</option>
					<option value="Pravara Institute of Medical Sciences">Pravara Institute of Medical Sciences</option>
					<option value="Presidency University (Kolkata)">Presidency University (Kolkata)</option>
					<option value="Presidency University (Karnataka)">Presidency University (Karnataka)</option>
					<option value="Pt. Bhagwat Dayal Sharma University of Health Sciences">Pt. Bhagwat Dayal Sharma University of Health Sciences</option>
					<option value="Pt. Ravishankar Shukla University">Pt. Ravishankar Shukla University</option>
					<option value="Pt. Sundarlal Sharma (Open) University">Pt. Sundarlal Sharma (Open) University</option>
					<option value="Pune University">Pune University</option>
					<option value="Punjab Agricultural University">Punjab Agricultural University</option>
					<option value="Punjab Engineering College">Punjab Engineering College</option>
					<option value="Punjab Technical University">Punjab Technical University</option>
					<option value="Punjab University">Punjab University</option>
					<option value="Punjabi University">Punjabi University</option>
					<option value="R.K. University">R.K. University</option>
					<option value="Rabindra Bharati University">Rabindra Bharati University</option>
					<option value="Raffles University">Raffles University</option>
					<option value="Rai Technology University">Rai Technology University</option>
					<option value="Rai University">Rai University</option>
					<option value="Raja Mansingh Tomar Music &amp; Arts University">Raja Mansingh Tomar Music &amp; Arts University</option>
					<option value="Rajasthan Agricultural University">Rajasthan Agricultural University</option>
					<option value="Rajasthan Ayurveda University">Rajasthan Ayurveda University</option>
					<option value="Rajasthan Technical University">Rajasthan Technical University</option>
					<option value="Rajasthan University">Rajasthan University</option>
					<option value="Rajasthan University of Health Sciences">Rajasthan University of Health Sciences</option>
					<option value="Rajasthan University of Veterinary &amp; Animal Sciences">Rajasthan University of Veterinary &amp; Animal Sciences</option>
					<option value="Rajendra Agricultural University">Rajendra Agricultural University</option>
					<option value="Rajiv Gandhi National Aviation University">Rajiv Gandhi National Aviation University</option>
					<option value="Rajiv Gandhi Prodoyogiki Vishwavidyalaya">Rajiv Gandhi Prodoyogiki Vishwavidyalaya</option>
					<option value="Rajiv Gandhi University">Rajiv Gandhi University</option>
					<option value="Rajiv Gandhi University of Health Sciences">Rajiv Gandhi University of Health Sciences</option>
					<option value="Rajiv Gandhi University of Knowledge Technologies">Rajiv Gandhi University of Knowledge Technologies</option>
					<option value="Rajmata Vijayaraje Scindia Krishi Vishwavidyalaya">Rajmata Vijayaraje Scindia Krishi Vishwavidyalaya</option>
					<option value="Raksha Shakti University">Raksha Shakti University</option>
					<option value="Rama University">Rama University</option>
					<option value="Ramakrishna Mission Vivekananda Educational and Research Institute">Ramakrishna Mission Vivekananda Educational and Research Institute</option>
					<option value="Ranchi University">Ranchi University</option>
					<option value="Rani Channamma University">Rani Channamma University</option>
					<option value="Rani Durgavati Vishwavidyalaya">Rani Durgavati Vishwavidyalaya</option>
					<option value="Rashtriya Sanskrit Sansthan">Rashtriya Sanskrit Sansthan</option>
					<option value="Rashtriya Sanskrit Vidyapeeth">Rashtriya Sanskrit Vidyapeeth</option>
					<option value="Ravenshaw University">Ravenshaw University</option>
					<option value="Rayalaseema University">Rayalaseema University</option>
					<option value="Reva University">Reva University</option>
					<option value="RKDF University">RKDF University</option>
					<option value="S.R.M. Institute of Science and Technology">S.R.M. Institute of Science and Technology</option>
					<option value="Sai Nath University">Sai Nath University</option>
					<option value="Sam Higginbottom Institute of Agriculture, Technology and Sciences">Sam Higginbottom Institute of Agriculture, Technology and Sciences</option>
					<option value="Sambalpur University">Sambalpur University</option>
					<option value="Sampurnanand Sanskrit Vishwavidyalaya">Sampurnanand Sanskrit Vishwavidyalaya</option>
					<option value="Sangam University">Sangam University</option>
					<option value="Sant Gadge Baba Amravati University">Sant Gadge Baba Amravati University</option>
					<option value="Sant Longowal Institute of Engineering and Technology (SLIET)">Sant Longowal Institute of Engineering and Technology (SLIET)</option>
					<option value="Santosh University">Santosh University</option>
					<option value="Sardar Vallabhbhai National Institute of Technology">Sardar Vallabhbhai National Institute of Technology</option>
					<option value="Sardar Patel University">Sardar Patel University</option>
					<option value="Sardar Patel University of Police, Security &amp; Criminal Justice">Sardar Patel University of Police, Security &amp; Criminal Justice</option>
					<option value="Sardar Vallabhbhai Patel University of Agriculture and Technology">Sardar Vallabhbhai Patel University of Agriculture and Technology</option>
					<option value="Sarguja University">Sarguja University</option>
					<option value="Satavahana University">Satavahana University</option>
					<option value="Sathyabama Institute of Science and Technology">Sathyabama Institute of Science and Technology</option>
					<option value="Saurashtra University">Saurashtra University</option>
					<option value="Saveetha Institute of Medical and Technical Sciences">Saveetha Institute of Medical and Technical Sciences</option>
					<option value="School of Planning &amp; Architecture">School of Planning &amp; Architecture</option>
					<option value="Shanmugha Arts, Science, Technology &amp; Research Academy (SASTRA)">Shanmugha Arts, Science, Technology &amp; Research Academy (SASTRA)</option>
					<option value="Sharda University">Sharda University</option>
					<option value="Shekhawati University">Shekhawati University</option>
					<option value="Sher-e-Kashmir University of Agricultural Science &amp; Technology, Chatha JAMMU &amp; KASHMIR">Sher-e-Kashmir University of Agricultural Science &amp; Technology, Chatha JAMMU &amp; KASHMIR</option>
					<option value="Sher-e-Kashmir University of Agricultural Science &amp; Technology, Srinagar JAMMU &amp; KASHMIR">Sher-e-Kashmir University of Agricultural Science &amp; Technology, Srinagar JAMMU &amp; KASHMIR</option>
					<option value="Shiksha ‘O’ Anusandhan">Shiksha ‘O’ Anusandhan</option>
					<option value="Shiv Nadar University">Shiv Nadar University</option>
					<option value="Shivaji University">Shivaji University</option>
					<option value="Shobhit University">Shobhit University</option>
					<option value="Shobit Institute of Engineering &amp; Technology">Shobit Institute of Engineering &amp; Technology</option>
					<option value="Shoolini University of Biotechnology and Management Sciences">Shoolini University of Biotechnology and Management Sciences</option>
					<option value="Shree Guru Gobind Singh Tricentenary University">Shree Guru Gobind Singh Tricentenary University</option>
					<option value="Shree Sankaracharya University of Sanskrit">Shree Sankaracharya University of Sanskrit</option>
					<option value="Shree Somnath Sanskrit University">Shree Somnath Sanskrit University</option>
					<option value="Shri Jagannath Sanskrit Vishwavidyalaya">Shri Jagannath Sanskrit Vishwavidyalaya</option>
					<option value="Shri Jagdish Prasad Jhabarmal Tibrewala University">Shri Jagdish Prasad Jhabarmal Tibrewala University</option>
					<option value="Shri Lal Bahadur Shastri Rashtriya Sanskrit Vidyapeetha">Shri Lal Bahadur Shastri Rashtriya Sanskrit Vidyapeetha</option>
					<option value="Shri Mata Vaishno Devi University">Shri Mata Vaishno Devi University</option>
					<option value="Shri Ramasamy memorial University">Shri Ramasamy memorial University</option>
					<option value="Shri Ramswaroop Memorial University">Shri Ramswaroop Memorial University</option>
					<option value="Shri Venkateshwara University">Shri Venkateshwara University</option>
					<option value="Shridhar University">Shridhar University</option>
					<option value="Sidho-Kanho-Birsha University">Sidho-Kanho-Birsha University</option>
					<option value="Sido Kanhu Murmu University">Sido Kanhu Murmu University</option>
					<option value="Sikkim- Manipal University of Health, Medical &amp; Technological Sciences">Sikkim- Manipal University of Health, Medical &amp; Technological Sciences</option>
					<option value="Sikkim University">Sikkim University</option>
					<option value="Singhania University">Singhania University</option>
					<option value="Sir Padmpat Singhania University">Sir Padmpat Singhania University</option>
					<option value="Smt. Nathibai Damodar Thackersey Women’s University">Smt. Nathibai Damodar Thackersey Women’s University</option>
					<option value="Solapur University">Solapur University</option>
					<option value="South Asian University">South Asian University</option>
					<option value="Sree Chitra Tirunal Institute of Medical Science &amp; Technology">Sree Chitra Tirunal Institute of Medical Science &amp; Technology</option>
					<option value="Sri Balaji Vidyapeeth">Sri Balaji Vidyapeeth</option>
					<option value="Sri Chandrasekharendra Saraswathi Viswa Mahavidyalaya">Sri Chandrasekharendra Saraswathi Viswa Mahavidyalaya</option>
					<option value="Sri Dev Suman Uttarakhand Vishwavidyalay">Sri Dev Suman Uttarakhand Vishwavidyalay</option>
					<option value="Sri Devraj Urs Academy of Higher Education and Research">Sri Devraj Urs Academy of Higher Education and Research</option>
					<option value="Sri Guru Granth Sahib World University">Sri Guru Granth Sahib World University</option>
					<option value="Sri Krishnadevaraya University">Sri Krishnadevaraya University</option>
					<option value="Sri Padmavati Mahila Vishwavidyalayam">Sri Padmavati Mahila Vishwavidyalayam</option>
					<option value="Sri Ramachandra Medical College and Research Institute">Sri Ramachandra Medical College and Research Institute</option>
					<option value="Sri Sai University">Sri Sai University</option>
					<option value="Sri Sathya Sai Institute of Higher Learning">Sri Sathya Sai Institute of Higher Learning</option>
					<option value="Sri Satya Sai University of Technology &amp; Medical Sciences">Sri Satya Sai University of Technology &amp; Medical Sciences</option>
					<option value="Sri Siddhartha Academy of Higher Education">Sri Siddhartha Academy of Higher Education</option>
					<option value="Sri Sri University">Sri Sri University</option>
					<option value="Sri Venkateswara Institute of Medical Sciences">Sri Venkateswara Institute of Medical Sciences</option>
					<option value="Sri Venkateswara University">Sri Venkateswara University</option>
					<option value="Sri Venkateswara Vedic University">Sri Venkateswara Vedic University</option>
					<option value="Sri Venkateswara Veterinary University">Sri Venkateswara Veterinary University</option>
					<option value="Srimanta Sankaradeva University of Health Sciences">Srimanta Sankaradeva University of Health Sciences</option>
					<option value="SRM University Delhi - NCR">SRM University Delhi - NCR</option>
					<option value="St. Peter’s Institute of Higher Education and Research">St. Peter’s Institute of Higher Education and Research</option>
					<option value="Sumandeep Vidyapeeth">Sumandeep Vidyapeeth</option>
					<option value="Sunrise University">Sunrise University</option>
					<option value="Suresh Gyan Vihar University">Suresh Gyan Vihar University</option>
					<option value="Swami Rama Himalayan University">Swami Rama Himalayan University</option>
					<option value="Swami Ramanand Teerth Marathwada University">Swami Ramanand Teerth Marathwada University</option>
					<option value="Swami Vivekanand Subharti University">Swami Vivekanand Subharti University</option>
					<option value="Swami Vivekananda University">Swami Vivekananda University</option>
					<option value="Swami Vivekananda Yoga Anusandhana Samsthana">Swami Vivekananda Yoga Anusandhana Samsthana</option>
					<option value="Swarnim Gujarat Sports University">Swarnim Gujarat Sports University</option>
					<option value="Symbiosis International (Deemed University)">Symbiosis International (Deemed University)</option>
					<option value="T.M. University">T.M. University</option>
					<option value="Tamilnadu Teacher Education University">Tamilnadu Teacher Education University</option>
					<option value="Tamil University">Tamil University</option>
					<option value="Tamilnadu Agricultural University">Tamilnadu Agricultural University</option>
					<option value="Tamilnadu Dr. Ambedkar Law University">Tamilnadu Dr. Ambedkar Law University</option>
					<option value="Tamilnadu Dr. M.G.R. Medical University">Tamilnadu Dr. M.G.R. Medical University</option>
					<option value="Tamilnadu Fisheries University">Tamilnadu Fisheries University</option>
					<option value="Tamilnadu Music and Fine Arts University">Tamilnadu Music and Fine Arts University</option>
					<option value="Tamilnadu National Law School">Tamilnadu National Law School</option>
					<option value="Tamilnadu Open University">Tamilnadu Open University</option>
					<option value="Tamilnadu Physical Education and Sports University">Tamilnadu Physical Education and Sports University</option>
					<option value="Tamilnadu Veterinary &amp; Animal Sciences University">Tamilnadu Veterinary &amp; Animal Sciences University</option>
					<option value="Tantia University">Tantia University</option>
					<option value="Tata Institute of Fundamental Research">Tata Institute of Fundamental Research</option>
					<option value="Tata Institute of Social Sciences">Tata Institute of Social Sciences</option>
					<option value="Team Lease Skills University">Team Lease Skills University</option>
					<option value="Techno Global University MADHYA PRADESH">Techno Global University MADHYA PRADESH</option>
					<option value="Techno Global University MEGHALAYA">Techno Global University MEGHALAYA</option>
					<option value="Techno India University">Techno India University</option>
					<option value="Teerthanker Mahaveer University">Teerthanker Mahaveer University</option>
					<option value="Telangana University">Telangana University</option>
					<option value="TERI School of Advanced Studies">TERI School of Advanced Studies</option>
					<option value="Tezpur University">Tezpur University</option>
					<option value="Thapar Institute of Engineering &amp; Technology">Thapar Institute of Engineering &amp; Technology</option>
					<option value="The Assam Kaziranga University">The Assam Kaziranga University</option>
					<option value="The Bengal Engineering &amp; Science University">The Bengal Engineering &amp; Science University</option>
					<option value="The English and Foreign Languages University">The English and Foreign Languages University</option>
					<option value="The Global Open University">The Global Open University</option>
					<option value="The Glocal University">The Glocal University</option>
					<option value="The Indira Gandhi National Tribal University">The Indira Gandhi National Tribal University</option>
					<option value="Indira Gandhi Technological and Medical Sciences University">Indira Gandhi Technological and Medical Sciences University</option>
					<option value="The Institute of Chartered Financial Analysts of India University JHARKHAND">The Institute of Chartered Financial Analysts of India University JHARKHAND</option>
					<option value="The Institute of Chartered Financial Analysts of India University MEGHALAYA">The Institute of Chartered Financial Analysts of India University MEGHALAYA</option>
					<option value="The Institute of Chartered Financial Analysts of India University MIZORAM">The Institute of Chartered Financial Analysts of India University MIZORAM</option>
					<option value="The Institute of Chartered Financial Analysts of India University NAGALAND">The Institute of Chartered Financial Analysts of India University NAGALAND</option>
					<option value="The Institute of Chartered Financial Analysts of India University SIKKIM">The Institute of Chartered Financial Analysts of India University SIKKIM</option>
					<option value="The Rajiv Gandhi National University of Law">The Rajiv Gandhi National University of Law</option>
					<option value="The Rashtrasant Tukadoji Maharaj Nagpur University">The Rashtrasant Tukadoji Maharaj Nagpur University</option>
					<option value="The West Bengal National University of Juridical Science">The West Bengal National University of Juridical Science</option>
					<option value="The West Bengal University of Health Sciences">The West Bengal University of Health Sciences</option>
					<option value="Thiruvalluvar University">Thiruvalluvar University</option>
					<option value="Thunchath Ezhuthachan Malayalam University">Thunchath Ezhuthachan Malayalam University</option>
					<option value="Tilak Maharashtra Vidyapeeth">Tilak Maharashtra Vidyapeeth</option>
					<option value="Tripura University">Tripura University</option>
					<option value="Tumkur University">Tumkur University</option>
					<option value="U.P. King George’s University of Dental Science">U.P. King George’s University of Dental Science</option>
					<option value="U.P. Rajarshi Tandon Open University">U.P. Rajarshi Tandon Open University</option>
					<option value="UKA Tarsadia University">UKA Tarsadia University</option>
					<option value="University of Agricultural Sciences, Bangalore">University of Agricultural Sciences, Bangalore</option>
					<option value="University of Agricultural Sciences, Dharwad">University of Agricultural Sciences, Dharwad</option>
					<option value="University of Allahabad">University of Allahabad</option>
					<option value="University of Engineering &amp; Management">University of Engineering &amp; Management</option>
					<option value="University of Hyderabad">University of Hyderabad</option>
					<option value="University of Kota">University of Kota</option>
					<option value="University of Patanjali">University of Patanjali</option>
					<option value="University of Petroleum and Energy Studies">University of Petroleum and Energy Studies</option>
					<option value="University of Science &amp; Technology">University of Science &amp; Technology</option>
					<option value="University of Technology &amp; Management">University of Technology &amp; Management</option>
					<option value="Utkal University">Utkal University</option>
					<option value="Utkal University of Culture">Utkal University of Culture</option>
					<option value="Uttar Banga Krishi Vishwavidyalaya">Uttar Banga Krishi Vishwavidyalaya</option>
					<option value="Uttar Pradesh Viklang Uddhar Dr. Shakuntala Misra University">Uttar Pradesh Viklang Uddhar Dr. Shakuntala Misra University</option>
					<option value="Uttarakhand Ayurved University">Uttarakhand Ayurved University</option>
					<option value="Uttarakhand Open University">Uttarakhand Open University</option>
					<option value="Uttarakhand Sanskrit University">Uttarakhand Sanskrit University</option>
					<option value="Uttarakhand University of Horticulture &amp; Forestry">Uttarakhand University of Horticulture &amp; Forestry</option>
					<option value="Uttaranchal University">Uttaranchal University</option>
					<option value="Uttarakhand Technical University">Uttarakhand Technical University</option>
					<option value="Vardhman Mahaveer Open University">Vardhman Mahaveer Open University</option>
					<option value="Veer Bahadur Singh Purvanchal University">Veer Bahadur Singh Purvanchal University</option>
					<option value="Veer Kunwar Singh University">Veer Kunwar Singh University</option>
					<option value="Veer Narmad South Gujarat University">Veer Narmad South Gujarat University</option>
					<option value="Veer Surendra Sai University of Technology">Veer Surendra Sai University of Technology</option>
					<option value="Vel Tech Rangarajan Dr. Sagunthala R &amp; D Institute of Science and Technology">Vel Tech Rangarajan Dr. Sagunthala R &amp; D Institute of Science and Technology</option>
					<option value="Vel`s Institute of Science, Technology &amp; Advanced Studies (VISTAS)">Vel`s Institute of Science, Technology &amp; Advanced Studies (VISTAS)</option>
					<option value="Vellore Institute of Technology">Vellore Institute of Technology</option>
					<option value="Venkateshwara Open University">Venkateshwara Open University</option>
					<option value="Vidya Sagar University">Vidya Sagar University</option>
					<option value="Vignan`s Foundation for Science, Technology and Research">Vignan`s Foundation for Science, Technology and Research</option>
					<option value="Vijayanagara Sri Krishnadevaraya University">Vijayanagara Sri Krishnadevaraya University</option>
					<option value="Vikram Simhapuri University">Vikram Simhapuri University</option>
					<option value="Vikram University">Vikram University</option>
					<option value="Vinayaka Mission’s Research Foundation">Vinayaka Mission’s Research Foundation</option>
					<option value="Vinayaka Missions Sikkim University">Vinayaka Missions Sikkim University</option>
					<option value="Vinoba Bhave University">Vinoba Bhave University</option>
					<option value="Vishwa Bharati University">Vishwa Bharati University</option>
					<option value="Visvesvaraya Technological University">Visvesvaraya Technological University</option>
					<option value="Visvesvaraya National Institute of Technology MAHARASHTRA">Visvesvaraya National Institute of Technology MAHARASHTRA</option>
					<option value="Vivekananda Global University">Vivekananda Global University</option>
					<option value="West Bengal State University">West Bengal State University</option>
					<option value="West Bengal University of Animal and Fishery Sciences">West Bengal University of Animal and Fishery Sciences</option>
					<option value="West Bengal University of Technology">West Bengal University of Technology</option>
					<option value="William Carey University">William Carey University</option>
					<option value="Xavier University">Xavier University</option>
					<option value="Yashwant Rao Chavan Maharashtra Open University">Yashwant Rao Chavan Maharashtra Open University</option>
					<option value="Yenepoya University">Yenepoya University</option>
					<option value="YMCA University of Science &amp; Technology">YMCA University of Science &amp; Technology</option>
					<option value="Yogi Vemana University">Yogi Vemana University</option>